name: Build and Release Flutter APK

on:
  push:
    tags:
      - 'v*'  # Runs only when a tag like v1.0.0 is pushed

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Use your Flutter version
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APKs
        run: flutter build apk --split-per-abi

      - name: Upload APKs to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apks
          path: build/app/outputs/apk/release/*.apk

  release:
    name: Publish Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built APKs
        uses: actions/download-artifact@v4
        with:
          name: flutter-apks
          path: build/app/outputs/apk/release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/apk/release/*.apk
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Automated Flutter release build."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
